### ISSUE TITLE
Issue on Users page

### ISSUE THREAD

**Issue by AlexFloresVeliz** [rupeshbasnet/MusicianApp#29]
When clicking on users, the information from the database is displayed on the page. 

**Bug can be found here:** https://young-garden-19844.herokuapp.com/users @David-Bohl 

I am not signed in if it helps.

![screen shot 2018-04-21 at 1 36 38 pm](https://user-images.githubusercontent.com/23161228/39087068-13252f5a-4569-11e8-81aa-ec360bf2a3e3.png)

**Comment by David-Bohl** [comment]
Thanks for pointing that out, I can't believe we missed it!  We'll fix it ASAP !

**Comment by AlexFloresVeliz** [comment]
Saw the changes. Awesome job @David-Bohl and awesome project!
